import { contentStore, readJson, escapeHtml, safeJson, stripHtml, formatDateFr, absoluteUrl } from "./_cms-utils.mjs";

const base="https://amberatlas.solar";
function header(active=""){
return `<header class="nav-wrap"><div class="container nav"><a class="brand" href="/" aria-label="Amber Atlas"><img alt="Amber Atlas logo" src="/logo.png"><div class="brand-title">Amber Atlas</div></a><div class="nav-right"><nav class="nav-links" aria-label="Navigation principale"><a href="/#top">À propos</a><a href="/#oferta">Offre</a><a href="/#branze">Secteurs</a><a href="/#realizacje">Solutions</a><a class="${active==='conseils'?'calculator-link':''}" href="/conseils/">Conseils</a><a class="${active==='faq'?'calculator-link':''}" href="/faq-photovoltaique-maroc/">FAQ</a><a class="calculator-link" href="/calculator/">Calculateur solaire</a><a href="/#kontakt">Contact</a></nav><div class="lang-switcher"><a class="lang-btn active" href="/" lang="fr">FR</a><a class="lang-btn" href="/ar/" lang="ar">AR</a><a class="lang-btn" href="/en/" lang="en">EN</a><a class="lang-btn" href="/pl/" lang="pl">PL</a></div></div></div></header>`}
function footer(){return `<footer><div class="container footer-inner"><div class="footer-copy">© Amber Atlas · Copyright 2026</div><div class="footer-links"><a href="/conseils/">Conseils</a><a href="/faq-photovoltaique-maroc/">FAQ</a></div><a class="footer-login" href="/admin/">Connexion</a></div></footer>`}
function page({title,description,canonical,body,schema,active=""}){
return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(description)}"><link rel="canonical" href="${escapeHtml(canonical)}"><meta property="og:type" content="website"><meta property="og:title" content="${escapeHtml(title)}"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:url" content="${escapeHtml(canonical)}"><meta property="og:image" content="${base}/logo.png"><meta name="theme-color" content="#0d1726"><link rel="icon" type="image/png" href="/logo.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cairo:wght@500;600;700;800&family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/css/amber-atlas-premium.css"><link rel="stylesheet" href="/assets/css/content-hub.css">${schema?`<script type="application/ld+json">${safeJson(schema)}</script>`:""}</head><body class="lang-fr content-hub-page">${header(active)}${body}${footer()}</body></html>`}
async function conseilsIndex(store){
  const items=(await readJson(store,"articles/index.json",[])).filter(x=>x.status==="published").sort((a,b)=>String(b.date||"").localeCompare(String(a.date||"")));
  const cards=items.length?`<div class="content-grid">${items.map(x=>`<article class="article-card">${x.imageUrl?`<a class="article-card-media" href="/conseils/${encodeURIComponent(x.slug)}/"><img src="${escapeHtml(x.imageUrl)}" alt="${escapeHtml(x.imageAlt||x.title)}" loading="lazy"></a>`:""}<div class="article-card-body"><div class="article-meta"><span>${escapeHtml(formatDateFr(x.date))}</span><span>·</span><span>${escapeHtml(x.author||"Amber Atlas")}</span></div><h2><a href="/conseils/${encodeURIComponent(x.slug)}/">${escapeHtml(x.title)}</a></h2><p>${escapeHtml(x.excerpt||"")}</p><a class="article-card-link" href="/conseils/${encodeURIComponent(x.slug)}/">Lire l’article →</a></div></article>`).join("")}</div>`:`<div class="empty-state"><h2>Les premiers articles arrivent bientôt</h2><p>Nous préparons des analyses pratiques sur le photovoltaïque, le stockage d’énergie et la rentabilité des projets pour les entreprises au Maroc.</p></div>`;
  const body=`<main><section class="content-hero"><div class="container"><div class="kicker">Expertise Amber Atlas</div><h1>Conseils photovoltaïques pour les entreprises au Maroc</h1><p>Analyses, guides et réponses pratiques pour préparer un investissement solaire adapté à votre activité, votre consommation et votre localisation.</p></div></section><section class="content-main"><div class="container">${cards}<div class="cta-box content-cta"><div><h3>Vous préparez un projet photovoltaïque ?</h3><p>Utilisez notre calculateur ou contactez l’équipe Amber Atlas pour une première analyse de votre site.</p></div><div><a class="btn btn-primary" href="/calculator/">Calculateur solaire</a></div></div></div></section></main>`;
  return page({title:"Conseils photovoltaïques au Maroc | Amber Atlas",description:"Guides et analyses sur le photovoltaïque, le stockage d’énergie et l’autoconsommation pour les entreprises au Maroc.",canonical:`${base}/conseils/`,body,active:"conseils"});
}
async function articlePage(store,slug){
  const item=await readJson(store,`articles/${slug}.json`,null);if(!item||item.status!=="published")return notFound();
  const canonical=`${base}/conseils/${encodeURIComponent(item.slug)}/`;const description=item.excerpt||stripHtml(item.content).slice(0,230);
  const schema={"@context":"https://schema.org","@type":"Article",headline:item.title,description,datePublished:item.date,dateModified:item.updatedAt||item.date,mainEntityOfPage:canonical,author:{"@type":"Person",name:item.author||"Amber Atlas"},publisher:{"@type":"Organization",name:"Amber Atlas",logo:{"@type":"ImageObject",url:`${base}/logo.png`}},...(item.imageUrl?{image:absoluteUrl(item.imageUrl)}:{})};
  const body=`<main><section class="content-main"><article class="article-shell"><div class="breadcrumbs"><a href="/">Accueil</a> / <a href="/conseils/">Conseils</a> / ${escapeHtml(item.title)}</div><header class="article-header"><div class="kicker">Conseils Amber Atlas</div><h1>${escapeHtml(item.title)}</h1><div class="article-meta"><span>${escapeHtml(formatDateFr(item.date))}</span><span>·</span><span>${escapeHtml(item.author||"Amber Atlas")}</span></div>${description?`<p class="article-lead">${escapeHtml(description)}</p>`:""}</header>${item.imageUrl?`<img class="article-cover" src="${escapeHtml(item.imageUrl)}" alt="${escapeHtml(item.imageAlt||item.title)}">`:""}<div class="article-content">${item.content}</div><div class="article-actions"><a class="btn btn-secondary" href="/conseils/">Tous les conseils</a><a class="btn btn-primary" href="/#kontakt">Parler de votre projet</a></div></article></section></main>`;
  return page({title:`${item.title} | Amber Atlas`,description,canonical,body,schema,active:"conseils"});
}
async function faqPage(store){
  const items=(await readJson(store,"faq/index.json",[])).filter(x=>x.status==="published").sort((a,b)=>(a.order||0)-(b.order||0));
  const list=items.length?`<div class="faq-list">${items.map((x,i)=>`<details class="faq-item"${i===0?' open':''}><summary>${escapeHtml(x.question)}</summary><div class="faq-answer">${x.answer}${x.imageUrl?`<img class="faq-image" src="${escapeHtml(x.imageUrl)}" alt="${escapeHtml(x.imageAlt||x.question)}" loading="lazy">`:""}</div></details>`).join("")}</div>`:`<div class="empty-state"><h2>La FAQ est en préparation</h2><p>Les réponses aux questions les plus fréquentes sur les installations photovoltaïques au Maroc seront publiées prochainement.</p></div>`;
  const schema=items.length?{"@context":"https://schema.org","@type":"FAQPage",mainEntity:items.map(x=>({"@type":"Question",name:x.question,acceptedAnswer:{"@type":"Answer",text:stripHtml(x.answer)}}))}:null;
  const body=`<main><section class="content-hero"><div class="container"><div class="kicker">Questions fréquentes</div><h1>FAQ sur le photovoltaïque au Maroc</h1><p>Des réponses claires aux questions des entreprises, hôtels, exploitations agricoles et sites industriels qui étudient un projet solaire.</p></div></section><section class="content-main"><div class="container">${list}<div class="cta-box content-cta"><div><h3>Vous n’avez pas trouvé votre réponse ?</h3><p>Décrivez votre projet à l’équipe Amber Atlas ou utilisez le calculateur solaire.</p></div><div><a class="btn btn-primary" href="/#kontakt">Nous contacter</a></div></div></div></section></main>`;
  return page({title:"FAQ photovoltaïque au Maroc | Amber Atlas",description:"Réponses aux questions fréquentes sur les panneaux solaires, l’autoconsommation, le stockage et les projets photovoltaïques au Maroc.",canonical:`${base}/faq-photovoltaique-maroc/`,body,schema,active:"faq"});
}
function notFound(){const body=`<main class="not-found"><div class="container"><div class="kicker">Erreur 404</div><h1>Article introuvable</h1><p class="section-sub">Cette publication n’existe pas ou n’est pas encore publiée.</p><div class="article-actions" style="justify-content:center"><a class="btn btn-primary" href="/conseils/">Retour aux conseils</a></div></div></main>`;return {html:page({title:"Article introuvable | Amber Atlas",description:"Article introuvable.",canonical:`${base}/conseils/`,body,active:"conseils"}),status:404}}
export default async(req)=>{
  let path=new URL(req.url).pathname; if(!path.endsWith("/")) path += "/"; path=path.replace(/\/{2,}/g,"/"); const store=contentStore();let result;
  if(path==="/faq-photovoltaique-maroc/")result=await faqPage(store);
  else if(path==="/conseils/")result=await conseilsIndex(store);
  else {const m=path.match(/^\/conseils\/([^/]+)\/$/);result=m?await articlePage(store,decodeURIComponent(m[1])):notFound()}
  const status=typeof result==="object"?result.status:200;const html=typeof result==="object"?result.html:result;
  return new Response(html,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"public, max-age=0, must-revalidate","x-content-type-options":"nosniff"}});
};
export const config={path:["/conseils","/conseils/","/conseils/:slug","/conseils/:slug/","/faq-photovoltaique-maroc","/faq-photovoltaique-maroc/"]};
